Develop
pluwiq/home-zoo pull request #4
Opened 2024-07-22 20:24 UTC by pluwiq

2024-07-22 21:45 UTC, TsikhanauDzmitry requested changes

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +    puts "6. Exit"
Почему нельзя это вывести одной строкой, но с отступами?

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +def add_animal(cats, dogs)
Не думаю, что размер этого метода хоть как-то удовлетворяет стайл-гайду. Что говорит RuboCop про это?

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +def add_animal(cats, dogs)
Вообще, давай напишем сервис, который будет добавлять животное? В Ruby on Rails этот паттерн называется Service Objects. Думаю мини-версию мы сможем реализовать

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +  end
Выглядит не красиво и без руби-сахара. А если вот так попробовать:
```
return puts 'Unknown type of animal!' unless %w[cat dog].include?(animal_type)
```

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +def add_animal(cats, dogs)
Совет по декомпозиции: каждый ввод какого-то поля - отдельный метод. А вообще идеально было бы познакомиться с `Single Responsibility Principle` и `Open/Closed Principle`: есть общий класс, который занимается добавлением поля, но т.к. каждое поле имеет уникальные проверки, то нужно создать дочерние сервисные классы, которые будут дополнять основной класс

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +  end
Мне не нравится данный блок кода. Думаю его можно попробовать оптимизировать к методу вида:
```
  def primer
    puts "Enter animal name (letters only):"
    until (name = gets.chomp).match?(/\A[a-zA-Z]+\z/)
      puts "Error: Name should contain only letters." unless name.match?(/\A[a-zA-Z]+\z/)
    end

    name
  end
```

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +  end
Аналогичные замечания для других полей

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
А зачем в файле `animal_info` был добавлен такой же метод?

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Думаю, что это можно объединить в 1 цикл, который идет сразу по 2 массивам одновременно

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +def show_all_animals(cats, dogs)
Все последующие методы нужно разделить по классам, а основные запросы объединить м помощью модуля

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Думаю, что данный метод должен возвращать животное (как объект), а не информацию по нему. Тогда мы сможем следовать DRY принципу и использовать данный метод в других методах

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +  animal = (cats + dogs).find { |animal| animal.name.downcase == name.downcase }
Очень непонятный нейминг переменных, думаю, что лучше было бы давать более явные имена им с точки зрения "откуда они у нас появились"

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Тогда данный метод должен либо возвращать `объект класса`, либо `nil`

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Думаю, что исходя из нового смысла этого метода, было бы круто реализовать его через обработчик ошибок https://stackify.com/rescue-exceptions-ruby/

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Т.к. в будущем у нас будет правильный `find_animal` метод, то данный метод сократится до 2 строк

2024-07-22 21:45 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Данный метод - сборник всех предыдущих методов

2024-07-23 05:49 UTC, pluwiq commented on animal_info.rb
> +def animal_info(animal)
если `animal` не  является объектом класса `Animal` или его подклассов, то при вызове `animal_info(animal)`
произойдет ошибка NoMethodError.

2024-07-23 05:54 UTC, pluwiq commented on animal_info.rb
> +def show_all_animals(animals)
если параметр `animals` не является массивом, произойдет ошибка `NoMethodError`, 
т.к объект не поддерживает итерацию методом `each`.

2024-07-23 06:01 UTC, pluwiq commented on animal.rb
> +  end
класс `Animal` служит базовым классом, который может быть унаследован другими классами **(Cat, Dog, ...).** 
Базовый класс предоставляет общие атрибуты. Свойства `:wool_color, :weight `специфичны для подклассов. Они определяются и инициализируются в конструкторах подклассов ,
и каждый класс должен иметь только те атрибуты и методы, которые относятся непосредственно к его зоне ответственности.

2024-07-24 11:56 UTC, TsikhanauDzmitry requested changes

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +  def self.find_animal_by_passport(cats, dogs, passport)
1. Обязательно ли всегда передавать собак и котов? Нельзя ли как-то упростить абсолютно все методы?
2. Ранее я просил не только в инициализации использовать строгие параметры, но еще и в методах, чтобы было удобнее

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +    if animal
В Ruby можно круто объединять такие строчки:
```
if (animal = find_animal_by_passport(cats, dogs, passport))
```

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      cats.delete(animal) || dogs.delete(animal)
Можешь расписать пожалуйста, как работает эта строчка?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +    animal = find_animal_by_passport(cats, dogs, passport)
В этом и в предыдущем методе есть повторяющийся код, который можно было бы вынести в отдельный метод. Так же, как идея для оптимизации и более понятного кода: делать методы типа
```
def delete_animal_by(passport: nil)
```

Так мы сможем явно понимать, кого мы удаляем. Так же при вызове метода можно будет сделать что-то типа:
```
delete_animal_by(passport: get_passport), где get_passport - это новый метод ввода паспорта
```

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      animal.instance_variable_set(:@weight, new_weight)
Интересные методы вызываются. Можешь рассказать пожалуйста, что они делают?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      animal.instance_variable_set(:@weight, new_weight)
Думаю, что создавать дополнительные локальные переменные не имеет такой уж необходимости, потому можно сразу в методах и вызывать сервис

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +    end
Очень не люблю каскадность `if/else` блоков. Было бы круче позвращать `else` блок (он тут как раз 1 строка) если не будет выполняться условие, а потом программа отрабатывает так как и должна

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_utils.rb
> +    animals.each { |animal| animal_info(animal) }
Думаю, что эти строчки можно объединить. Как считаешь?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_utils.rb
> +end
Как работает `self.method` для модуля?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on animal_utils.rb
> +  end
Не логичнее ли делать этот метод не для всего класса, а только для объекта?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on cat.rb
> +    super(name: name, age: age, passport_number: passport_number)
В последних Ruby версиях есть классная штука, что если у нас локальные переменные имеют теже имена, что и параметры в методе, то можно просто указывать символы параметров. Ruby - умный и поймет, что ты хотела передать

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on cat.rb
> +    self.weight = weight
Почему ранее были использованы `инстансные переменные`, а сейчас `self`?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on dog.rb
Аналогичные замечания с `class Cat`

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Зачем этот метод тут?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +end
Зачем этот метод тут?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +  (cats + dogs).map(&:passport_number)
Расскажи пожалуйста про блок `.map(&:passport_number)`. Как он работает? Чем `map` отличается от `each`?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on home_zoo.rb
> +    Services::CreateAnimalService.new(cats: cats, dogs: dogs, existing_passports: existing_passports).call
1. Строчки можно объединить
2. Если у нас есть 2 массива котов и собак, то, наверное, передавать все паспорта, или же 2 массива не нужно?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +    end
Есть в сервисах пара приколов по структуре:
1. Если мы создаем и инициализируем сервис, то у нас в `public` есть `initialize` и `call` методы
2. Если нам нужно проделать какие-то void'овские манипуляции и инициализирование внутри сервиса не нужно, то вместо первых методов у нас будет только 1 метод: `perform`

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +    end
Берем за правило, что то, что мы возвращаем в методе, мы отделяем сверху пустой строчкой

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +  end
Почему данный метод в `privat` блоке у `BaseService`?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +    def ask_with_validation(prompt, validation_regex, error_message)
Странное название метода? Почему именно такое?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +      passport_number = Services::ValidatePassportNumberService.new(@existing_passports).call
Выносим в отдельный метод, который вернет hash необходимых полей

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +      end
1. Выносим в отдельный метод
2. После того, как это животное было создано, то мы сможем его найти ? Если да, то как? Будет ли оно зранится в `@cats`, `@dogs`? Если хранится там, то почему мы не возвращаем ничего из `call#CreateAnimalService`?

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +    end
Думаю, что правильнее было бы сделать этот метод не просто запросом на ввод, а обычной валидацией, но не на поле объекта, а на его тип

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/validate_passport_number_service.rb
> +    def initialize(existing_passport_numbers = [])
Не правильно указала строгие параметры

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/validate_passport_number_service.rb
> +        puts "Error: Passport number should contain only digits and must be unique."
Думаю, что тут логичнее вернуть ошибку в случае неудачи, а потом вернуть номер паспорта

2024-07-24 11:56 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
## Сейчас поговорим про оптимизацию сервисов

Как мы можем заметить наши дочерние сервисы для ввода имеют 3 разных параметра при вызове `ask_with_validation` метода. Думаю, что можно в данном случае удалить все остальные сервисы и оставить 3: `Base`, `ValidatePassportNumber` и`CreateAnimal`. В последнем сделать метод, который подбирает нужный массив параметров относительно поля, которое мы вводим, и возвращает проверенное поле. Так мы максимально сократим наш код до минимального, красивого и рабочего

2024-07-24 11:57 UTC, TsikhanauDzmitry commented on animal.rb
> +  attr_accessor :age, :wool_color, :weight
@pluwiq напоминаю

2024-07-24 11:58 UTC, TsikhanauDzmitry commented on animal.rb
> +  def initialize(name, age)
@pluwiq напоминаю про `"во всех методах"`

2024-07-24 12:00 UTC, TsikhanauDzmitry commented on animal_info.rb
> +def show_all_animals(animals)
@pluwiq не вижу, чтобы проверки на то, чтобы такого не было

2024-07-24 12:00 UTC, TsikhanauDzmitry commented on animal.rb
> +  end
@pluwiq жду ответ

2024-07-24 19:03 UTC, pluwiq commented on animal_manager.rb
> +      cats.delete(animal) || dogs.delete(animal)
оператор `||` выполняет логическую операцию "или" между выражениями и возвращает первое истинное значение, которое он находит (или последнее выражение, если все предыдущие ложные). 
если `cats.delete(animal) `возвращает объект, то оператор` || `завершает выполнение и возвращает объект.
если `cats.delete(animal) `возвращает `nil`, то оператор выполняет вторую часть выражения `dogs.delete(animal)`.

2024-07-24 19:18 UTC, pluwiq commented on animal_manager.rb
> +      animal.instance_variable_set(:@weight, new_weight)
метод instance_variable_set используется для установки значения переменной экземпляра объекта и позволяет напрямую изменить значение переменной экземпляра, которая может быть закрытой для прямого доступа (attr_accessor, attr_reader).
animal - объект у которого нужно установить значение переменной экземпляра
:@age || :@weight - имя переменной экземпляра
new_age || new_weight - значение которое необходимо присвоить переменной экземпляра

2024-07-24 19:57 UTC, pluwiq commented on animal_utils.rb
> +end
Когда метод объявляется с использованием `self `в модуле, это делает его методом самого модуля. Это означает, что мы можем вызвать этот метод напрямую на модуле, как на объекте.
Методы `animal_info `и `show_all_animals` в `AnimalUtils` являются утилитарными (не привязаны к состоянию объекта), так как они просто выводят информацию и не требуют хранения состояния между вызовами.

2024-07-24 20:28 UTC, pluwiq commented on cat.rb
> +    self.weight = weight
Инстансные переменные используются напрямую для инициализации, мы обходим методы доступа и работаем непосредственно с переменными экземпляра. Использование `self.wool_color = wool_color` и `self.weight = weight` вызывает методы доступа, обеспечивая возможность добавления логики в этих методах в будущем.

2024-07-25 07:51 UTC, pluwiq commented on home_zoo.rb
> +end
метод используется для получения всех номеров паспорта для всех кошек и собак, чтобы обеспечить уникальность номера при добавлении нового животного. Это имеет место быть для валидации, чтобы не допустить дублирования номеров.
(метод возвращает массив всех паспортных номеров, объединяя списки кошек и собак)

2024-07-25 08:01 UTC, pluwiq commented on home_zoo.rb
> +  (cats + dogs).map(&:passport_number)
метод `map `используется для создания нового массива путем выполнения блока для каждого элемента исходного массива, где каждый результат выполнения блока становится элементом нового массива.
метод `each` используется для итерирования по каждому элементу массива. метод each возвращает исходный массив (после выполнения блока для каждого его элемента), а не новый. 

синтаксис .map(&:passport_number) является сокращением для вызова метода на каждом элементе массива.  `&:passport_number` эквивалентно `{ |animal| animal.passport_number }`

код объединяет массивы в один, для каждого элемента в новом массиве вызывает метод `passport_number` и создает новый массив, содержащий результаты вызова метода `passport_number` для каждого элемента.

2024-07-25 08:21 UTC, pluwiq commented on services/base_service.rb
> +  end
метод объявлен в `private` потому что он предназначен для использования только внутри класса BaseService и его подклассов. Данная часть реализации не должна быть доступна извне. Мы сохраняем принципы инкапсуляции (скрываем детали реализации класса от внешнего мира и поддерживаем четкое разделение между интерфейсом класса и его реализацией). Также Пользователи должны взаимодействовать только с методом `call`.

2024-07-25 08:27 UTC, pluwiq commented on services/base_service.rb
> +    def ask_with_validation(prompt, validation_regex, error_message)
название метода выбрано потому, что оно описывает функциональность: метод "спрашивает" у пользователя ввод, а затем "проверяет" введенные данные на соответствие заданному регулярному выражению. Как вариант наверное было бы лучше использовать что-то вроде `prompt_and_validate`, но я не уверена.

2024-07-25 09:26 UTC, pluwiq commented on services/create_animal_service.rb
> +      end
Мы сможем найти созданное животное. После того как оно было создано и добавлено в соответствующий список, можно искать его в списках `@cats `или `@dogs`. Списки `@cats `и `@dogs` являются инстанс переменными класса `CreateAnimalService`, и после добавления объекта в эти списки, объект там сохраняется.

в новой версии проекта метод call будет возвращать созданное животное. Тогда мы сможем получить ссылку на созданное животное и использовать ее для дальнейших операций (поиск или изменение его атрибутов)

2024-07-25 09:44 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +    def ask_with_validation(prompt, validation_regex, error_message)
Может быть лучше `get_field_with_validation` ?

2024-07-25 11:14 UTC, pluwiq commented on animal.rb
> +  end
изначально были мысли сделать список животных, где не все имеют цвет шерсти или вес как релевантные атрибуты. Но на данный момент все животные, которые будут использовать базовый класс, должны иметь атрибуты `:wool_color `и `:weight`. Код будет исправлен.

2024-07-27 08:49 UTC, TsikhanauDzmitry requested changes

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal.rb
> +    end
Это можно написать одной строкой

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal.rb
> +  def initialize(name:, age:, passport_number:, wool_color: nil, weight: nil)
Идея понятно. Все круто, но может чисто логичнее (с точки зрения бизнеса), указывать цвет шерсти по умолчанию, как "лысый"? А вес рандомное чисто из какого-нибудь промежутка

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +  class << self
Расскажи мне про данный момент. Что делает `class << self` ?

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      passport ||= get_passport
Опиши мне 3 случая, что мне вернется в паспорте:
1. Я передал в параметрах метода паспорт
2. Я получил get_passport
3. get_passport вернул мне nil

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      unless (animal = find_animal_by_passport(passport: passport))
Вроде бы ранее я говорил, что можно вызывать методы так:
```
find_animal_by_passport(passport:)
```
При условии, что у нас есть локальная переменная `passport`

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      yield(animal) if animal && block_given?
Как работает `yield`?

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +    end
Что делает данный метод? Какая его основная функция?

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +      end
1. Можно объединить 39 и 40 строчки
2. Избавляемся от каскадности. Выводим ошибку в случае неудачи

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_manager.rb
> +    end
Не является ли он избыточным?

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_utils.rb
> +end
Забыла пустую строчку в конце файла

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on animal_utils.rb
> +      end
Можно в одну строчку это написать

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/base_service.rb
> +      end
Можно реализовать одной строкой

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +        passport_number: Services::ValidatePassportNumberService.new(existing_passport_numbers: @existing_passports).perform
Если у нас есть и `new` и метод, то этот метод не `perform`, a `call`

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +      }
Вынеси это как приватную константу, а потому "заморозь её". Ниже отпиши, зачем её нужно замораживать

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +        cat = Cat.new(**attributes)
Зачем тут `**`?

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/create_animal_service.rb
> +end
Пустая строчка)

2024-07-27 08:49 UTC, TsikhanauDzmitry commented on services/validate_passport_number_service.rb
> +            prompt: "Enter passport number (digits only):",
Напоминаю, что строчки с двойными кавычками мы используем только для интерполяции. Проверь этот момент во всех файлах

2024-07-27 13:29 UTC, pluwiq commented on animal_manager.rb
> +  class << self
`class << self` открывает скрытый класс (синглтон-класс) для объекта. Данный класс позволяет определять методы, которые будут уникальными для данного объекта. 

Когда мы используем `class << self` внутри класса или модуля, мы можем определить методы, которые будут доступны непосредственно на уровне класса, а не на уровне экземпляра класса.

2024-07-27 14:01 UTC, pluwiq commented on animal_manager.rb
> +      passport ||= get_passport
1. передавая паспорт в параметрах, `passport` будет равен переданному значению и` get_passport `не будет вызван, так как `passport `уже имеет значение.
2. если мы вызываем метод без передачи параметра, то метод вызовет `get_passport` и вернет введенное пользователем значение
3. паспорт не был передан, вызываем метод `get_passport`, который возвращает `nil`. метод продолжит выполнение и попытается найти животное по `nil` в `find_animal_by_passport` и вернет` nil`. Сообщение `"Animal with passport number nil was not found."` будет выведено.

2024-07-27 14:24 UTC, pluwiq commented on animal_manager.rb
> +      yield(animal) if animal && block_given?
yield используется для передачи управления и выполнения кода блока, переданного методу. Когда метод содержит yield, он ожидает, что при его вызове будет передан блок кода. Если блок передан, то yield вызывает этот блок, передавая ему любые аргументы, если это необходимо.

2024-07-27 14:37 UTC, pluwiq commented on animal_manager.rb
> +    end
Метод `with_animal` предназначен для поиска животного по номеру паспорта и выполнения блока кода с найденным животным. Основная функция метода заключается в:

1. Получении номера паспорта, если он не был передан.
2. Поиске животного по этому номеру паспорта.
3. Выполнении блока кода с найденным животным, если животное было найдено и блок был передан.

по поводу избыточности не знаю.

2024-07-27 14:57 UTC, pluwiq commented on services/create_animal_service.rb
> +      }
заморозить константу можно для предотвращения изменений. Замораживание объектов делает их неизменяемыми, что помогает избежать случайных или преднамеренных изменений данных которые не должны изменяться во время выполнения программы.

2024-07-27 15:06 UTC, pluwiq commented on services/create_animal_service.rb
> +        cat = Cat.new(**attributes)
`**` используются для распаковки хэша в аргументы метода. В методе `create_animal`, `**attributes `позволяет передать элементы хэша `attributes` как отдельные ключевые аргументы в конструкторы классов `Cat` и` Dog`.

2024-07-29 15:04 UTC, TsikhanauDzmitry approved these changes

2024-07-30 12:07 UTC, merged